### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: ClientId longer than 23 characters

### ISSUE THREAD

**Issue by santosh75** [mqtt/mqtt.github.io#17]
Exception in thread "main" java.lang.IllegalArgumentException: ClientId longer than 23 characters
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:257)
	at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:222)
	at Subscriber$.main(mqtt_subscriber.scala:31)
	at Subscriber.main(mqtt_subscriber.scala)

Even unable to download the jar file using SBT

**Comment by knolleary** [comment]
This repository is for the mqtt wiki. It is not associated with any clients.

You should raise the issue against the appropriate paho repo.
